-- AlterTable
ALTER TABLE `Ticket` MODIFY `status` ENUM('OPEN', 'RESOLVED', 'CLOSED') NULL DEFAULT 'OPEN';

-- AlterTable
ALTER TABLE `User` MODIFY `status` ENUM('ACTIVE', 'PENDING', 'BLOCKED') NULL DEFAULT 'PENDING';
